-- GENERATED by scripts/dev/generate-a1-catalog.mjs — do not hand-edit.
-- Seeds tenant zero's catalog. Re-runnable: upserts on (company_id, service_key).
-- Change rates in the catalog tables from now on, not in @a1/pricing-engine.

do $$
declare
  v_company uuid;
  v_org uuid;
begin
  select id, organization_id into v_company, v_org
  from public.companies where slug = 'a1-coatings';
  if v_company is null then
    raise notice 'company a1-coatings not found; nothing seeded';
    return;
  end if;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'ceramic', 'Ceramic Coating', 'per_measure', 3500, 0, 'ft', null, null, null, null, null, null, null, false, 0)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'ceramic_second_layer', 'Ceramic Coating — second layer', 'per_measure', 800, 0, 'ft', null, null, null, null, null, null, null, false, 1)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'ceramic_teak_ceramic', 'Teak Ceramic', 'flat', 30000, 0, null, null, null, null, null, null, null, null, false, 2)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'ceramic_interior_ceramic', 'Interior Ceramic', 'flat', 15000, 0, null, null, null, null, null, null, null, null, false, 3)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'graphene', 'Graphene Coating', 'per_measure', 4000, 0, 'ft', null, null, null, null, null, null, null, false, 4)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'graphene_second_layer', 'Graphene Coating — second layer', 'per_measure', 1000, 0, 'ft', null, null, null, null, null, null, null, false, 5)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'graphene_teak_graphene', 'Teak Graphene', 'flat', 35000, 0, null, null, null, null, null, null, null, null, false, 6)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

end $$;
