-- GENERATED by scripts/dev/generate-a1-catalog.mjs — do not hand-edit.
-- Seeds tenant zero's catalog. Re-runnable: upserts on (company_id, service_key).
-- Change rates in the catalog tables from now on, not in @a1/pricing-engine.

do $$
declare
  v_company uuid;
  v_org uuid;
begin
  select id, organization_id into v_company, v_org
  from public.companies where slug = 'a1-marine-storage';
  if v_company is null then
    raise notice 'company a1-marine-storage not found; nothing seeded';
    return;
  end if;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'outdoor_storage', 'Outdoor winter storage (season)', 'per_measure', 5000, 75000, null, null, null, null, null, null, null, null, true, 0)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'shrink_wrap', 'Shrink wrapping', 'per_measure', 2500, 37500, null, null, null, null, null, null, null, null, true, 1)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'winterization_outboard', 'Winterization — outboard', 'per_unit_declining', 27500, 0, 'engine', 0.75, null, null, null, null, null, null, false, 2)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'winterization_sterndrive', 'Winterization — sterndrive', 'per_unit_declining', 40000, 0, 'engine', 0.75, null, null, null, null, null, null, false, 3)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'winterization_inboard', 'Winterization — inboard', 'per_unit_declining', 44500, 0, 'engine', 0.75, null, null, null, null, null, null, false, 4)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'fall_detail', 'Fall detail (wash & wax)', 'per_measure', 2400, 36000, null, null, null, null, null, null, null, null, false, 5)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'spring_commissioning', 'Spring commissioning', 'flat', 26500, 0, null, null, null, null, null, null, null, null, false, 6)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'ceramic_upgrade', 'Winter ceramic coating upgrade', 'per_measure', 8500, 0, null, null, null, null, null, null, null, 26, false, 7)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'battery_storage', 'Battery storage & charging', 'per_unit', 10000, 0, 'battery', null, null, null, null, null, null, null, false, 8)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'trailer_storage', 'Trailer storage (season)', 'flat', 20000, 0, null, null, null, null, null, null, null, null, false, 9)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'pwc_storage', 'PWC storage (season)', 'per_unit', 45000, 0, 'PWC', null, null, null, null, null, 6, null, false, 10)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'pwc_winterization', 'PWC winterization', 'per_unit', 17500, 0, 'PWC', null, null, null, null, null, 6, null, false, 11)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'oil_change_outboard', 'Oil change — outboard', 'per_unit', 17500, 0, 'engine', null, null, null, null, null, 8, null, false, 12)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'oil_change_pwc', 'Oil change — PWC', 'per_unit', 15000, 0, 'PWC', null, null, null, null, null, 6, null, false, 13)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'extended_storage', 'Extended storage (after April 30)', 'per_unit', 10000, 0, 'vessel-month', null, null, null, null, null, 24, null, false, 14)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'transport_local', 'Transport — local', 'per_unit', 15000, 0, 'trip', null, null, null, null, null, 4, null, false, 15)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'transport_regional', 'Transport — regional', 'per_unit', 25000, 0, 'trip', null, null, null, null, null, 4, null, false, 16)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'transport_extended', 'Transport — extended', 'per_unit', 37500, 0, 'trip', null, null, null, null, null, 4, null, false, 17)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'transport_beyond_per_km', 'Transport — beyond extended band', 'per_measure', 350, 0, null, null, null, null, null, null, null, 2000, false, 18)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_items (company_id, organization_id, service_key, label, pricing_type, rate_cents, minimum_cents, unit_label, additional_unit_multiplier, tiers, rate_bands, modifier_groups, review_rules, max_quantity, max_measure, surcharge_eligible, sort_order)
  values (v_company, v_org, 'spring_wrap_removal', 'Spring wrap removal & disposal', 'tiered_by_measure', 0, 0, null, null, '[{"maxMeasure":26,"rateCents":15000},{"maxMeasure":null,"rateCents":20000}]'::jsonb, null, null, null, null, null, false, 19)
  on conflict (company_id, service_key) do update set label = excluded.label, pricing_type = excluded.pricing_type, rate_cents = excluded.rate_cents, minimum_cents = excluded.minimum_cents, unit_label = excluded.unit_label, additional_unit_multiplier = excluded.additional_unit_multiplier, tiers = excluded.tiers, rate_bands = excluded.rate_bands, modifier_groups = excluded.modifier_groups, review_rules = excluded.review_rules, max_quantity = excluded.max_quantity, max_measure = excluded.max_measure, surcharge_eligible = excluded.surcharge_eligible, sort_order = excluded.sort_order;

  insert into public.service_catalog_bundles (company_id, organization_id, bundle_key, label, discount_pct, service_keys)
  values (v_company, v_org, 'winter_ready', 'Winter Ready', 8, array['outdoor_storage', 'shrink_wrap']::text[])
  on conflict (company_id, bundle_key) do update set label = excluded.label, discount_pct = excluded.discount_pct, service_keys = excluded.service_keys;

  insert into public.service_catalog_bundles (company_id, organization_id, bundle_key, label, discount_pct, service_keys)
  values (v_company, v_org, 'winter_ready_plus', 'Winter Ready Plus', 10, array['outdoor_storage', 'shrink_wrap', 'winterization_*']::text[])
  on conflict (company_id, bundle_key) do update set label = excluded.label, discount_pct = excluded.discount_pct, service_keys = excluded.service_keys;

  insert into public.service_catalog_bundles (company_id, organization_id, bundle_key, label, discount_pct, service_keys)
  values (v_company, v_org, 'full_care', 'Full Care', 12, array['outdoor_storage', 'shrink_wrap', 'winterization_*', 'fall_detail', 'spring_commissioning']::text[])
  on conflict (company_id, bundle_key) do update set label = excluded.label, discount_pct = excluded.discount_pct, service_keys = excluded.service_keys;

  insert into public.service_catalog_surcharges (company_id, organization_id, variant_key, label, per_measure_cents)
  values (v_company, v_org, 'pontoon', 'pontoon', 800)
  on conflict (company_id, variant_key) do update set label = excluded.label, per_measure_cents = excluded.per_measure_cents;

  insert into public.service_catalog_surcharges (company_id, organization_id, variant_key, label, per_measure_cents)
  values (v_company, v_org, 'tritoon', 'tritoon', 1000)
  on conflict (company_id, variant_key) do update set label = excluded.label, per_measure_cents = excluded.per_measure_cents;

end $$;
