import { describe, expect, it, vi } from "vitest";

/**
 * The auto-quote review window.
 *
 * Once SELF_SERVE_QUOTES_ENABLED is on, quotes go out with no human in the loop.
 * The only window where a wrong one can be fixed for free is while it is SENT or
 * VIEWED: void it and the customer never pays it. After they approve, the number
 * is one they agreed to; after they pay, the fix is a refund.
 *
 * So this list is deliberately narrow. Including approved or paid quotes would
 * make it a list of things you cannot act on, which is how a review queue stops
 * being read.
 */

const rows: Array<Record<string, unknown>> = [];
const captured: { eq: Array<[string, unknown]>; inFilters: Array<[string, unknown[]]> } = {
  eq: [],
  inFilters: [],
};

vi.mock("@/server/services/shared", () => ({}));

function fakeChain() {
  const chain: Record<string, unknown> = {
    select: () => chain,
    eq: (col: string, val: unknown) => {
      captured.eq.push([col, val]);
      return chain;
    },
    in: (col: string, vals: unknown[]) => {
      captured.inFilters.push([col, vals]);
      return chain;
    },
    order: () => chain,
    limit: () => Promise.resolve({ data: rows, error: null }),
  };
  return chain;
}

const { listQuotes, REVIEWABLE_STATUSES } = await import("@/server/services/quotes/service");

const ctx = {
  organizationId: "org1",
  actorProfileId: null,
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  supabase: { from: () => fakeChain() } as any,
};

describe("the review window is sent + viewed, and nothing else", () => {
  it("excludes approved — the customer has agreed to that number", () => {
    expect(REVIEWABLE_STATUSES).not.toContain("approved");
  });

  it("excludes deposit_paid — money has moved; the fix is a refund", () => {
    expect(REVIEWABLE_STATUSES).not.toContain("deposit_paid");
  });

  it("excludes cancelled — already actioned", () => {
    expect(REVIEWABLE_STATUSES).not.toContain("cancelled");
  });

  it("is exactly the two states where voiding still costs nothing", () => {
    expect([...REVIEWABLE_STATUSES].sort()).toEqual(["sent", "viewed"]);
  });
});

describe("filters reach the query", () => {
  it("scopes to auto-generated when asked", async () => {
    captured.eq.length = 0;
    captured.inFilters.length = 0;
    await listQuotes(ctx, { autoGenerated: true, statuses: REVIEWABLE_STATUSES });
    expect(captured.eq).toContainEqual(["auto_generated", true]);
    expect(captured.inFilters).toContainEqual(["status", ["sent", "viewed"]]);
  });

  it("always scopes to the organization", async () => {
    captured.eq.length = 0;
    await listQuotes(ctx, {});
    expect(captured.eq).toContainEqual(["organization_id", "org1"]);
  });

  it("applies no auto/status filter when none is asked for", async () => {
    captured.eq.length = 0;
    captured.inFilters.length = 0;
    await listQuotes(ctx, {});
    // The default list must stay the full list — the review view is opt-in.
    expect(captured.eq.map(([c]) => c)).not.toContain("auto_generated");
    expect(captured.inFilters).toHaveLength(0);
  });

  it("can ask for hand-written quotes specifically", async () => {
    captured.eq.length = 0;
    await listQuotes(ctx, { autoGenerated: false });
    expect(captured.eq).toContainEqual(["auto_generated", false]);
  });
});
