import { X, User, Calendar, Clock, Link2, MessageSquare, CheckCircle2, Circle, Zap, ArrowUpRight, FileText, Send } from "lucide-react";
import { cn } from "@/lib/utils";
import { useState } from "react";
import { SystemTraceChain, type SystemEvent } from "@/components/system/GlobalActivityFeed";

interface Task {
  id: string;
  title: string;
  description: string;
  status: string;
  priority: string;
  assignee: string;
  assigneeInitials: string;
  dueDate: string;
  company: string;
  linkedContact?: { name: string; id: string };
  linkedBooking?: string;
  autoGenerated?: string;
  overdue?: boolean;
  comments: number;
  subtasks?: { done: number; total: number };
}

const companyColors: Record<string, string> = {
  "A1 Marine Care": "bg-[hsl(var(--accent-blue))]/15 text-[hsl(var(--accent-blue))]",
  "RankLocal": "bg-[hsl(var(--accent-violet))]/15 text-[hsl(var(--accent-violet))]",
  "MarineMecca": "bg-[hsl(var(--success))]/15 text-[hsl(var(--success))]",
  "Vitatee": "bg-[hsl(var(--warning))]/15 text-[hsl(var(--warning))]",
};

const priorityConfig: Record<string, { bg: string; text: string; dot: string }> = {
  High: { bg: "bg-[hsl(var(--urgent))]/10", text: "text-[hsl(var(--urgent))]", dot: "bg-[hsl(var(--urgent))]" },
  Medium: { bg: "bg-[hsl(var(--warning))]/10", text: "text-[hsl(var(--warning))]", dot: "bg-[hsl(var(--warning))]" },
  Low: { bg: "bg-muted", text: "text-muted-foreground", dot: "bg-muted-foreground" },
};

const activityItems = [
  { type: "comment", user: "Kira Lam", text: "Confirmed with the client — proceeding as planned.", time: "2h ago", icon: MessageSquare },
  { type: "status", user: "System", text: "Status changed to In Progress", time: "4h ago", icon: Zap },
  { type: "link", user: "Marcus Reid", text: "Linked to booking: Vessel Inspection", time: "1d ago", icon: Link2 },
  { type: "created", user: "System", text: "Task auto-generated from new booking", time: "2d ago", icon: FileText },
];

const subtaskItems = [
  { title: "Verify inspection scope", done: true },
  { title: "Confirm inspector availability", done: false },
  { title: "Send pre-arrival documentation", done: false },
  { title: "Prepare safety checklist", done: true },
];

// System trace per task (simulated)
const taskTraces: Record<string, SystemEvent[]> = {
  "TSK-001": [
    { id: "tr1", type: "booking_created", title: "Booking created", detail: "Vessel Inspection — Pacific Voyager", company: "A1 Marine Care", timestamp: "2d ago" },
    { id: "tr2", type: "workflow_triggered", title: "Workflow triggered", detail: "New Booking Workflow", company: "A1 Marine Care", timestamp: "2d ago" },
    { id: "tr3", type: "task_created", title: "Task created", detail: "TSK-001 — Confirm vessel inspection details", company: "A1 Marine Care", timestamp: "2d ago" },
    { id: "tr4", type: "notification_sent", title: "Notification sent", detail: "Marcus Reid assigned", company: "A1 Marine Care", timestamp: "2d ago" },
  ],
  "TSK-006": [
    { id: "tr5", type: "stage_changed", title: "CRM stage changed", detail: "Active → Overdue", company: "A1 Marine Care", timestamp: "3d ago" },
    { id: "tr6", type: "workflow_triggered", title: "Workflow triggered", detail: "Overdue Invoice Alert", company: "A1 Marine Care", timestamp: "3d ago" },
    { id: "tr7", type: "task_created", title: "Task created", detail: "TSK-006 — Follow up on outstanding invoice", company: "A1 Marine Care", timestamp: "3d ago" },
  ],
  "TSK-012": [
    { id: "tr8", type: "contact_updated", title: "New contact added", detail: "Rachel Kim — RankLocal", company: "RankLocal", timestamp: "1d ago" },
    { id: "tr9", type: "workflow_triggered", title: "Workflow triggered", detail: "Lead Follow-Up", company: "RankLocal", timestamp: "1d ago" },
    { id: "tr10", type: "task_created", title: "Task created", detail: "TSK-012 — Send proposal to new lead", company: "RankLocal", timestamp: "1d ago" },
  ],
};

interface Props {
  task: Task;
  onClose: () => void;
  onNavigateContact: (id: string) => void;
  onNavigateCalendar: () => void;
}

export default function TaskDetailPanel({ task, onClose, onNavigateContact, onNavigateCalendar }: Props) {
  const [commentText, setCommentText] = useState("");
  const trace = taskTraces[task.id];

  return (
    <div className="fixed inset-0 z-50 flex justify-end">
      <div className="absolute inset-0 bg-black/40 backdrop-blur-sm" onClick={onClose} />
      <div className="relative w-[520px] h-full bg-[hsl(var(--surface-1))] border-l border-border overflow-y-auto animate-slide-in-right">
        {/* Header */}
        <div className="sticky top-0 z-10 bg-[hsl(var(--surface-1))]/95 backdrop-blur-md border-b border-border px-6 py-4">
          <div className="flex items-center justify-between">
            <div className="flex items-center gap-2">
              <span className="text-xs font-mono text-muted-foreground">{task.id}</span>
              {task.autoGenerated && (
                <span className="flex items-center gap-1 text-[10px] font-medium px-1.5 py-0.5 rounded bg-[hsl(var(--accent-violet))]/10 text-[hsl(var(--accent-violet))]">
                  <Zap className="w-2.5 h-2.5" />
                  Auto-generated
                </span>
              )}
            </div>
            <button onClick={onClose} className="p-1.5 rounded-lg hover:bg-[hsl(var(--surface-2))] transition-colors text-muted-foreground">
              <X className="w-4 h-4" />
            </button>
          </div>
          <h2 className="text-lg font-semibold text-foreground mt-2 leading-tight">{task.title}</h2>
        </div>

        <div className="px-6 py-5 space-y-6">
          {/* Overdue Banner */}
          {task.overdue && task.status !== "Completed" && (
            <div className="flex items-center gap-2 px-3 py-2 rounded-lg bg-[hsl(var(--urgent))]/8 border border-[hsl(var(--urgent))]/20">
              <Clock className="w-3.5 h-3.5 text-[hsl(var(--urgent))] animate-pulse" />
              <span className="text-xs font-medium text-[hsl(var(--urgent))]">This task is overdue — due {task.dueDate}</span>
            </div>
          )}

          {/* System Trace */}
          {trace && (
            <div className="space-y-2">
              <div className="flex items-center gap-2">
                <Zap className="w-3 h-3 text-[hsl(var(--accent-violet))]" />
                <h3 className="text-xs font-medium text-muted-foreground uppercase tracking-wider">System Trace</h3>
              </div>
              <div className="bg-[hsl(var(--surface-2))]/60 rounded-lg p-3 border border-border/50">
                <SystemTraceChain events={trace} />
              </div>
            </div>
          )}

          {/* Meta Grid */}
          <div className="grid grid-cols-2 gap-3">
            <div className="space-y-1">
              <span className="text-[11px] text-muted-foreground uppercase tracking-wider">Status</span>
              <div className="flex items-center gap-2">
                <span className={cn(
                  "text-sm font-medium",
                  task.status === "Blocked" ? "text-[hsl(var(--urgent))]" :
                  task.status === "In Progress" ? "text-[hsl(var(--accent-blue))]" :
                  task.status === "Completed" ? "text-[hsl(var(--success))]" : "text-foreground"
                )}>{task.status}</span>
              </div>
            </div>
            <div className="space-y-1">
              <span className="text-[11px] text-muted-foreground uppercase tracking-wider">Priority</span>
              <span className={cn("inline-flex items-center gap-1.5 text-xs font-medium px-2 py-0.5 rounded-md", priorityConfig[task.priority].bg, priorityConfig[task.priority].text)}>
                <span className={cn("w-1.5 h-1.5 rounded-full", priorityConfig[task.priority].dot)} />
                {task.priority}
              </span>
            </div>
            <div className="space-y-1">
              <span className="text-[11px] text-muted-foreground uppercase tracking-wider">Assignee</span>
              <div className="flex items-center gap-2">
                <div className="w-5 h-5 rounded-full bg-[hsl(var(--surface-3))] flex items-center justify-center text-[9px] font-semibold text-foreground">{task.assigneeInitials}</div>
                <span className="text-sm text-foreground">{task.assignee}</span>
              </div>
            </div>
            <div className="space-y-1">
              <span className="text-[11px] text-muted-foreground uppercase tracking-wider">Due Date</span>
              <span className={cn("text-sm", task.overdue && task.status !== "Completed" ? "text-[hsl(var(--urgent))] font-medium" : "text-foreground")}>{task.dueDate}</span>
            </div>
            <div className="space-y-1">
              <span className="text-[11px] text-muted-foreground uppercase tracking-wider">Company</span>
              <span className={cn("text-[11px] font-medium px-2 py-0.5 rounded-md", companyColors[task.company])}>{task.company}</span>
            </div>
          </div>

          {/* Description */}
          <div className="space-y-2">
            <h3 className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Description</h3>
            <p className="text-sm text-foreground/80 leading-relaxed">{task.description}</p>
          </div>

          {/* Linked Entities */}
          {(task.linkedContact || task.linkedBooking) && (
            <div className="space-y-2">
              <h3 className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Connected To</h3>
              <div className="space-y-2">
                {task.linkedContact && (
                  <button
                    onClick={() => onNavigateContact(task.linkedContact!.id)}
                    className="w-full flex items-center justify-between px-3 py-2.5 rounded-lg bg-[hsl(var(--surface-2))] border border-border hover:border-[hsl(var(--accent-blue))]/30 transition-all group"
                  >
                    <div className="flex items-center gap-2.5">
                      <div className="p-1.5 rounded-md bg-[hsl(var(--accent-blue))]/10">
                        <User className="w-3.5 h-3.5 text-[hsl(var(--accent-blue))]" />
                      </div>
                      <div className="text-left">
                        <p className="text-sm font-medium text-foreground">{task.linkedContact.name}</p>
                        <p className="text-[11px] text-muted-foreground">CRM Contact</p>
                      </div>
                    </div>
                    <ArrowUpRight className="w-3.5 h-3.5 text-muted-foreground group-hover:text-[hsl(var(--accent-blue))] transition-colors" />
                  </button>
                )}
                {task.linkedBooking && (
                  <button
                    onClick={onNavigateCalendar}
                    className="w-full flex items-center justify-between px-3 py-2.5 rounded-lg bg-[hsl(var(--surface-2))] border border-border hover:border-[hsl(var(--accent-violet))]/30 transition-all group"
                  >
                    <div className="flex items-center gap-2.5">
                      <div className="p-1.5 rounded-md bg-[hsl(var(--accent-violet))]/10">
                        <Calendar className="w-3.5 h-3.5 text-[hsl(var(--accent-violet))]" />
                      </div>
                      <div className="text-left">
                        <p className="text-sm font-medium text-foreground">{task.linkedBooking}</p>
                        <p className="text-[11px] text-muted-foreground">Calendar Booking</p>
                      </div>
                    </div>
                    <ArrowUpRight className="w-3.5 h-3.5 text-muted-foreground group-hover:text-[hsl(var(--accent-violet))] transition-colors" />
                  </button>
                )}
              </div>
            </div>
          )}

          {/* Subtasks */}
          {task.subtasks && (
            <div className="space-y-2">
              <div className="flex items-center justify-between">
                <h3 className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Subtasks</h3>
                <span className="text-[11px] text-muted-foreground tabular-nums">{task.subtasks.done}/{task.subtasks.total} complete</span>
              </div>
              <div className="space-y-1">
                {subtaskItems.slice(0, task.subtasks.total).map((st, i) => (
                  <div key={i} className="flex items-center gap-2.5 px-3 py-2 rounded-lg hover:bg-[hsl(var(--surface-2))] transition-colors cursor-pointer">
                    {st.done
                      ? <CheckCircle2 className="w-4 h-4 text-[hsl(var(--success))]" />
                      : <Circle className="w-4 h-4 text-muted-foreground" />
                    }
                    <span className={cn("text-sm", st.done ? "text-muted-foreground line-through" : "text-foreground")}>{st.title}</span>
                  </div>
                ))}
              </div>
            </div>
          )}

          {/* Activity */}
          <div className="space-y-2">
            <h3 className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Activity</h3>
            <div className="space-y-0">
              {activityItems.map((item, i) => (
                <div key={i} className="flex gap-3 py-2.5 relative">
                  {i < activityItems.length - 1 && <div className="absolute left-[13px] top-10 w-px h-[calc(100%-16px)] bg-border" />}
                  <div className={cn(
                    "w-[26px] h-[26px] rounded-full flex items-center justify-center shrink-0",
                    item.type === "comment" ? "bg-[hsl(var(--accent-blue))]/10" :
                    item.type === "status" ? "bg-[hsl(var(--accent-violet))]/10" : "bg-[hsl(var(--surface-3))]"
                  )}>
                    <item.icon className={cn(
                      "w-3 h-3",
                      item.type === "comment" ? "text-[hsl(var(--accent-blue))]" :
                      item.type === "status" ? "text-[hsl(var(--accent-violet))]" : "text-muted-foreground"
                    )} />
                  </div>
                  <div className="min-w-0">
                    <p className="text-sm text-foreground/80">
                      <span className="font-medium text-foreground">{item.user}</span>{" "}
                      {item.text}
                    </p>
                    <p className="text-[11px] text-muted-foreground mt-0.5">{item.time}</p>
                  </div>
                </div>
              ))}
            </div>
          </div>

          {/* Comment Input */}
          <div className="space-y-2">
            <h3 className="text-xs font-medium text-muted-foreground uppercase tracking-wider">Add Comment</h3>
            <div className="flex gap-2">
              <input
                type="text"
                value={commentText}
                onChange={(e) => setCommentText(e.target.value)}
                placeholder="Write a comment..."
                className="flex-1 bg-[hsl(var(--surface-2))] border border-border rounded-lg px-3 py-2 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-[hsl(var(--accent-blue))]/50"
              />
              <button className="p-2 rounded-lg bg-[hsl(var(--accent-blue))] text-white hover:bg-[hsl(var(--accent-blue))]/90 transition-colors active:scale-[0.97]">
                <Send className="w-4 h-4" />
              </button>
            </div>
          </div>

          {/* Actions */}
          <div className="flex gap-2 pt-2 border-t border-border">
            <button className="flex-1 py-2 rounded-lg text-xs font-medium bg-[hsl(var(--surface-2))] text-foreground hover:bg-[hsl(var(--surface-3))] transition-colors active:scale-[0.98]">
              Mark Complete
            </button>
            <button className="flex-1 py-2 rounded-lg text-xs font-medium bg-[hsl(var(--surface-2))] text-foreground hover:bg-[hsl(var(--surface-3))] transition-colors active:scale-[0.98]">
              Reassign
            </button>
            <button className="flex-1 py-2 rounded-lg text-xs font-medium bg-[hsl(var(--surface-2))] text-[hsl(var(--urgent))] hover:bg-[hsl(var(--urgent))]/10 transition-colors active:scale-[0.98]">
              Escalate
            </button>
          </div>
        </div>
      </div>
    </div>
  );
}
