import { randomBytes } from "node:crypto";

import {
  assertCompanyInOrganization,
  assertContactInOrganization,
  type TenantServiceContext,
} from "@/server/services/shared";
import { getQuotesConfig } from "./config";
import { assertTransition, type QuoteStatus } from "./lifecycle";
import { sendQuoteEmail, sendQuoteReplacedEmail } from "./notify";
import { priceQuoteForCompany, type QuotePricing, type QuotePricingInput } from "./pricing";

// quotes + quote_events aren't in the generated database.types.ts (no gen-types step),
// same as the jobber_/retell_ tables — access them via the client cast to any, shaping
// rows with the interfaces below. Regenerating database.types.ts restores typing
// (tracked in docs/stripe-quotes.md).
// eslint-disable-next-line @typescript-eslint/no-explicit-any
const tbl = (ctx: TenantServiceContext, name: string): any => (ctx.supabase as any).from(name);

export interface CreateQuoteInput {
  contactId?: string | null;
  companyId?: string | null;
  services: QuotePricingInput["services"];
  /** Hand-priced Care lines (restoration, detailing) — never engine-computed. */
  customLines?: QuotePricingInput["customLines"];
  hullType?: string;
  bundleId?: string;
  /** Customer-facing heading. Falls back to the org default template. */
  title?: string;
  /** The personal note at the top of the hosted page. */
  introMessage?: string;
  notes?: string;
  source?: string;
  /** Phase 5: set when the intake path generated this without a human. */
  autoGenerated?: boolean;
  sourceLeadId?: string | null;
  /** Server policy overrides — not exposed to clients; default from config. */
  taxRateBps?: number;
  depositRateBps?: number;
}

export type UpdateQuoteInput = Omit<CreateQuoteInput, "autoGenerated" | "sourceLeadId">;

export interface QuoteRow {
  id: string;
  organization_id: string;
  company_id: string | null;
  contact_id: string | null;
  public_token: string;
  quote_number: string | null;
  status: QuoteStatus;
  currency: string;
  title: string | null;
  intro_message: string | null;
  line_items: unknown;
  subtotal_cents: number;
  tax_cents: number;
  total_cents: number;
  deposit_cents: number;
  tax_rate_bps: number;
  deposit_rate_bps: number;
  bundle_id: string | null;
  input_snapshot: unknown;
  notes: string | null;
  source: string | null;
  expires_at: string | null;
  valid_until: string | null;
  sent_at: string | null;
  first_viewed_at: string | null;
  auto_generated: boolean;
  source_lead_id: string | null;
  supersedes: string | null;
  superseded_by: string | null;
  cancelled_at: string | null;
  cancel_reason: string | null;
  created_by: string | null;
  created_at: string;
  updated_at: string;
}

function genPublicToken(): string {
  return randomBytes(16).toString("hex");
}

/**
 * The default intro, used when the caller doesn't supply one. Deliberately
 * org-neutral — tenant-specific wording belongs in org settings, not in code
 * (A1 Marine Storage is tenant zero, not a special case).
 */
export function defaultIntroMessage(orgName?: string | null): string {
  const who = orgName?.trim() || "our team";
  return (
    `Thanks for your interest — here's the quote from ${who}.\n\n` +
    `Review the details below, tick any optional services you'd like included, ` +
    `then approve online to lock in your spot. Your total and deposit update as you choose.`
  );
}

/** Shape the pricing inputs kept verbatim for reprice / audit. */
function inputSnapshot(input: CreateQuoteInput) {
  return {
    services: input.services,
    customLines: input.customLines ?? [],
    hullType: input.hullType ?? null,
    bundleId: input.bundleId ?? null,
  };
}

/** The priced columns — shared by create, update and reprice so they can't drift apart. */
function pricedColumns(pricing: QuotePricing) {
  return {
    currency: pricing.currency,
    // lineItems carry `optional`, `selected` and `custom` per line, which is what the
    // Phase 3 page renders its checkboxes from.
    line_items: pricing.lineItems,
    subtotal_cents: pricing.subtotalCents,
    tax_cents: pricing.taxCents,
    total_cents: pricing.totalCents,
    deposit_cents: pricing.depositCents,
    tax_rate_bps: pricing.taxRateBps,
    deposit_rate_bps: pricing.depositRateBps,
    bundle_id: pricing.bundleId,
  };
}

/**
 * Price from the TENANT's catalog. Async because the catalog is per-company and
 * lives in the database — there is no built-in price list to fall back to.
 */
async function priceFrom(companyId: string, input: CreateQuoteInput): Promise<QuotePricing> {
  return priceQuoteForCompany(companyId, {
    services: input.services,
    customLines: input.customLines,
    hullType: input.hullType,
    bundleId: input.bundleId,
    taxRateBps: input.taxRateBps,
    depositRateBps: input.depositRateBps,
  });
}

/** Best-effort audit append — the quote itself is already durable. */
async function recordEvent(
  ctx: TenantServiceContext,
  quoteId: string,
  eventType: string,
  metadata: Record<string, unknown> = {},
): Promise<void> {
  try {
    await tbl(ctx, "quote_events").insert({
      organization_id: ctx.organizationId,
      quote_id: quoteId,
      event_type: eventType,
      actor_profile_id: ctx.actorProfileId,
      metadata,
    });
  } catch (err) {
    console.error(`[quotes] failed to record '${eventType}' event:`, err);
  }
}

/**
 * Create a quote: price it from the shared engine, persist the priced snapshot, and
 * append the 'created' audit event. Runs under the caller's RLS client (org members
 * may write), so the scope guards below turn an out-of-org contact/company into a
 * clean 400 rather than an RLS insert failure.
 *
 * Created as a DRAFT with no quote_number — numbers are allocated on send (see
 * sendQuote) so abandoned drafts don't burn customer-facing numbers.
 */
export async function createQuote(ctx: TenantServiceContext, input: CreateQuoteInput): Promise<QuoteRow> {
  await assertContactInOrganization(ctx, input.contactId ?? undefined);
  await assertCompanyInOrganization(ctx, input.companyId ?? undefined);

  // A quote must belong to a company: the catalog, the Stripe account and the
  // branding are all company-scoped, so a company-less quote cannot be priced.
  if (!input.companyId) {
    throw new Error("A quote needs a company — pricing, payment and branding are all per-company.");
  }
  const pricing = await priceFrom(input.companyId, input);
  const cfg = getQuotesConfig();
  const expiresAt = new Date(Date.now() + cfg.expiryDays * 24 * 60 * 60 * 1000).toISOString();

  const { data, error } = await tbl(ctx, "quotes")
    .insert({
      organization_id: ctx.organizationId,
      company_id: input.companyId ?? null,
      contact_id: input.contactId ?? null,
      public_token: genPublicToken(),
      status: "draft",
      title: input.title ?? null,
      intro_message: input.introMessage ?? null,
      ...pricedColumns(pricing),
      input_snapshot: inputSnapshot(input),
      notes: input.notes ?? null,
      source: input.source ?? null,
      expires_at: expiresAt,
      auto_generated: input.autoGenerated ?? false,
      source_lead_id: input.sourceLeadId ?? null,
      created_by: ctx.actorProfileId,
    })
    .select("*")
    .single();

  if (error) throw error;
  const quote = data as QuoteRow;

  await recordEvent(ctx, quote.id, "created", {
    subtotalCents: quote.subtotal_cents,
    totalCents: quote.total_cents,
    depositCents: quote.deposit_cents,
  });

  return quote;
}

/**
 * Re-price and update a quote from fresh inputs. Only legal while the customer has
 * not committed: once a quote is approved, its approved_line_items snapshot is what
 * we charge and owe work against, so editing it underneath them is refused.
 */
export async function updateQuote(
  ctx: TenantServiceContext,
  quoteId: string,
  input: UpdateQuoteInput,
): Promise<QuoteRow> {
  await assertContactInOrganization(ctx, input.contactId ?? undefined);
  await assertCompanyInOrganization(ctx, input.companyId ?? undefined);

  const existing = await getQuote(ctx, quoteId);
  if (!existing) throw new Error(`Quote ${quoteId} not found.`);
  if (!["draft", "sent", "viewed"].includes(existing.status)) {
    throw new Error(`Quote ${quoteId} is "${existing.status}" and can no longer be edited.`);
  }

  const companyId = input.companyId ?? existing.company_id;
  if (!companyId) throw new Error("A quote needs a company to be repriced.");
  const pricing = await priceFrom(companyId, input);

  const { data, error } = await tbl(ctx, "quotes")
    .update({
      company_id: input.companyId ?? null,
      contact_id: input.contactId ?? null,
      title: input.title ?? existing.title,
      intro_message: input.introMessage ?? existing.intro_message,
      ...pricedColumns(pricing),
      input_snapshot: inputSnapshot(input),
      notes: input.notes ?? existing.notes,
    })
    .eq("id", quoteId)
    .eq("organization_id", ctx.organizationId)
    .select("*")
    .single();

  if (error) throw error;
  const quote = data as QuoteRow;

  await recordEvent(ctx, quote.id, "repriced", {
    fromTotalCents: existing.total_cents,
    toTotalCents: quote.total_cents,
    fromDepositCents: existing.deposit_cents,
    toDepositCents: quote.deposit_cents,
  });

  return quote;
}

/**
 * Allocate the next per-org quote number (Q-2026-0001). Atomic upsert in Postgres,
 * so two concurrent sends cannot collide. Hard-fails rather than falling back to
 * null: a customer-facing quote without a number is worse than a failed send.
 */
async function allocateQuoteNumber(ctx: TenantServiceContext): Promise<string> {
  // eslint-disable-next-line @typescript-eslint/no-explicit-any
  const { data, error } = await (ctx.supabase as any).rpc("next_quote_number", {
    p_organization_id: ctx.organizationId,
  });
  if (error) throw error;
  if (typeof data !== "string" || data.length === 0) {
    throw new Error("next_quote_number returned no value.");
  }
  return data;
}

/**
 * Move a draft to sent: allocate its customer-facing number, stamp sent_at, and set
 * valid_until (default 30 days). Returns the row the Phase 3 email links to.
 */
export async function sendQuote(ctx: TenantServiceContext, quoteId: string): Promise<QuoteRow> {
  const existing = await getQuote(ctx, quoteId);
  if (!existing) throw new Error(`Quote ${quoteId} not found.`);
  assertTransition(existing.status, "sent");

  const cfg = getQuotesConfig();
  const now = new Date();
  const validUntil = new Date(now.getTime() + cfg.expiryDays * 24 * 60 * 60 * 1000).toISOString();
  // Keep an existing number on a re-send so the customer's reference doesn't change.
  const quoteNumber = existing.quote_number ?? (await allocateQuoteNumber(ctx));

  const { data, error } = await tbl(ctx, "quotes")
    .update({
      status: "sent",
      quote_number: quoteNumber,
      sent_at: now.toISOString(),
      valid_until: validUntil,
      expires_at: validUntil,
    })
    .eq("id", quoteId)
    .eq("organization_id", ctx.organizationId)
    .select("*")
    .single();

  if (error) throw error;
  const quote = data as QuoteRow;
  await recordEvent(ctx, quote.id, "sent", { quoteNumber, validUntil });

  // Email AFTER the status write: a mail failure must not leave a quote the
  // customer can open sitting in 'draft'. sendQuoteEmail throws, so the admin
  // learns immediately — the quote is sent and re-sending only re-mails it (the
  // number is kept, see above).
  await sendQuoteEmail(quote.id);

  return quote;
}

export async function getQuote(ctx: TenantServiceContext, quoteId: string): Promise<QuoteRow | null> {
  const { data, error } = await tbl(ctx, "quotes")
    .select("*")
    .eq("id", quoteId)
    .eq("organization_id", ctx.organizationId)
    .maybeSingle();
  if (error) throw error;
  return (data ?? null) as QuoteRow | null;
}

export async function listQuotes(
  ctx: TenantServiceContext,
  opts: { limit?: number } = {},
): Promise<QuoteRow[]> {
  const { data, error } = await tbl(ctx, "quotes")
    .select("*")
    .eq("organization_id", ctx.organizationId)
    .order("created_at", { ascending: false })
    .limit(Math.min(Math.max(opts.limit ?? 50, 1), 100));
  if (error) throw error;
  return (data ?? []) as QuoteRow[];
}

/**
 * Void-and-reissue — the revision mechanic.
 *
 * updateQuote refuses edits past 'viewed' because the amounts a customer saw are
 * what we'd owe work against. But "can you change it?" is the most common reply a
 * quote gets, so the answer is to replace rather than mutate: cancel what they saw
 * and issue a successor pre-filled from it.
 *
 * The old token keeps resolving — it renders a "this quote was replaced" state and
 * can never be approved (see derivePageState / isApprovable). Nothing is deleted,
 * so the record of what was offered when stays intact.
 *
 * The successor is a DRAFT with no quote number: sending it allocates a fresh one
 * under the normal rule, so the customer's new reference is unambiguous.
 */
export async function reissueQuote(
  ctx: TenantServiceContext,
  quoteId: string,
  opts: { reason?: string } = {},
): Promise<{ cancelled: QuoteRow; successor: QuoteRow }> {
  const existing = await getQuote(ctx, quoteId);
  if (!existing) throw new Error(`Quote ${quoteId} not found.`);
  if (existing.status === "cancelled") {
    throw new Error(`Quote ${quoteId} is already cancelled.`);
  }
  // deposit_paid/completed quotes have money against them — reissue is not the
  // tool for those; a refund is (Phase 4).
  assertTransition(existing.status as QuoteStatus, "cancelled");

  const snap = (existing.input_snapshot ?? {}) as Partial<CreateQuoteInput>;
  const now = new Date().toISOString();

  // 1. Successor first: if this fails, the original is untouched and still live.
  const successor = await createQuote(ctx, {
    contactId: existing.contact_id,
    companyId: existing.company_id,
    services: snap.services ?? [],
    customLines: snap.customLines ?? [],
    hullType: snap.hullType ?? undefined,
    bundleId: snap.bundleId ?? undefined,
    title: existing.title ?? undefined,
    introMessage: existing.intro_message ?? undefined,
    notes: existing.notes ?? undefined,
    source: existing.source ?? undefined,
  });

  const { error: linkErr } = await tbl(ctx, "quotes")
    .update({ supersedes: existing.id })
    .eq("id", successor.id)
    .eq("organization_id", ctx.organizationId);
  if (linkErr) throw linkErr;

  // 2. Now retire the original and point it forward.
  const { data, error } = await tbl(ctx, "quotes")
    .update({
      status: "cancelled",
      cancelled_at: now,
      cancel_reason: opts.reason ?? "Replaced by a revised quote",
      superseded_by: successor.id,
    })
    .eq("id", existing.id)
    .eq("organization_id", ctx.organizationId)
    .select("*")
    .single();
  if (error) throw error;

  const cancelled = data as QuoteRow;
  await recordEvent(ctx, cancelled.id, "cancelled", {
    reason: opts.reason ?? null,
    supersededBy: successor.id,
  });
  await recordEvent(ctx, successor.id, "reissued", { supersedes: cancelled.id });

  // Best-effort: both rows are already committed and correct. A mail failure
  // must not leave the reissue half-done — it is recorded as an event instead.
  await sendQuoteReplacedEmail(successor.id, opts.reason ?? null);

  return { cancelled, successor: { ...successor, supersedes: cancelled.id } as QuoteRow };
}

/**
 * Void a quote — retire it with no successor. (Use reissueQuote when a revised
 * replacement should be sent in its place.)
 */
export async function cancelQuote(
  ctx: TenantServiceContext,
  quoteId: string,
  opts: { reason?: string } = {},
): Promise<QuoteRow> {
  const existing = await getQuote(ctx, quoteId);
  if (!existing) throw new Error(`Quote ${quoteId} not found.`);
  if (existing.status === "cancelled") {
    throw new Error(`Quote ${quoteId} is already cancelled.`);
  }
  // deposit_paid/completed quotes have money against them — voiding is not the
  // tool for those; a refund is (Phase 4).
  assertTransition(existing.status as QuoteStatus, "cancelled");

  const now = new Date().toISOString();
  const { data, error } = await tbl(ctx, "quotes")
    .update({
      status: "cancelled",
      cancelled_at: now,
      cancel_reason: opts.reason ?? "Voided",
    })
    .eq("id", quoteId)
    .eq("organization_id", ctx.organizationId)
    .select("*")
    .single();
  if (error) throw error;

  const cancelled = data as QuoteRow;
  await recordEvent(ctx, cancelled.id, "cancelled", { reason: opts.reason ?? null });
  return cancelled;
}
