import { useMemo } from "react";
import { Link } from "react-router-dom";
import { Download, Sparkles, Phone, Zap, FileText, TrendingUp, CalendarCheck } from "lucide-react";
import {
  Bar,
  BarChart,
  CartesianGrid,
  Cell,
  ResponsiveContainer,
  Tooltip,
  XAxis,
  YAxis,
} from "recharts";
import { Button } from "@/components/ui/button";
import { DashboardCard } from "@/components/ui/DashboardCard";
import { EmptyState, ErrorBanner, LoadingRows, SkeletonCard } from "@/components/ui/StateViews";
import { useOrg } from "@/lib/org-context";
import { useAttribution } from "@/lib/api-hooks";
import { formatCents, formatDate, formatSeconds } from "@/lib/format";
import type { AttributionRow } from "@/lib/api-client";

const SOURCE_COLORS = [
  "hsl(var(--primary))",
  "hsl(var(--accent-violet))",
  "hsl(var(--success))",
  "hsl(var(--warning))",
  "hsl(var(--muted-foreground))",
];

function csvEscape(value: string): string {
  return /[",\n]/.test(value) ? `"${value.replace(/"/g, '""')}"` : value;
}

/** Build the export from the already-fetched rows — no separate export endpoint (Amendment 5). */
function rowsToCsv(rows: AttributionRow[]): string {
  const header = [
    "quote_id",
    "company_id",
    "contact_id",
    "first_touch_source",
    "first_touch_channel",
    "first_touch_at",
    "voice_ai_involved",
    "automation_involved",
    "auto_generated",
    "approved_cents",
    "paid_cents",
    "approved_at",
    "paid_at",
  ];
  const lines = rows.map((row) =>
    [
      row.quoteId,
      row.companyId ?? "",
      row.contactId ?? "",
      row.firstTouchSource,
      row.firstTouchChannel,
      row.firstTouchAt ?? "",
      String(row.voiceAiInvolved),
      String(row.automationInvolved),
      String(row.autoGenerated),
      String(row.approvedCents),
      String(row.paidCents),
      row.approvedAt ?? "",
      row.paidAt ?? "",
    ]
      .map((cell) => csvEscape(String(cell)))
      .join(","),
  );
  return [header.join(","), ...lines].join("\n");
}

function downloadCsv(filename: string, csv: string): void {
  const blob = new Blob([csv], { type: "text/csv;charset=utf-8;" });
  const url = URL.createObjectURL(blob);
  const anchor = document.createElement("a");
  anchor.href = url;
  anchor.download = filename;
  document.body.appendChild(anchor);
  anchor.click();
  anchor.remove();
  URL.revokeObjectURL(url);
}

function SummaryTile({
  label,
  value,
  hint,
  accent,
}: {
  label: string;
  value: string;
  hint?: string;
  accent?: string;
}) {
  return (
    <div className="bg-secondary/40 rounded-lg p-4">
      <p className={`text-2xl font-bold tabular-nums ${accent ?? "text-foreground"}`}>{value}</p>
      <p className="text-xs font-medium text-foreground mt-1">{label}</p>
      {hint && <p className="text-[11px] text-muted-foreground mt-0.5">{hint}</p>}
    </div>
  );
}

export default function ReportsAttributionPage() {
  const { organizationId, companyId, isValid } = useOrg();
  const params = useMemo(() => ({ companyId: companyId ?? undefined, rows: true }), [companyId]);
  const { data, isLoading, isError, refetch } = useAttribution(organizationId, params);

  const summary = data?.summary;
  const rows = data?.rows ?? [];
  const range = data?.range;

  const chartData = useMemo(
    () =>
      (summary?.bySource ?? []).map((entry) => ({
        source: entry.key,
        paid: entry.paidCents / 100,
        approved: entry.approvedCents / 100,
        count: entry.count,
      })),
    [summary],
  );

  if (!isValid) {
    return (
      <div className="max-w-[1440px] mx-auto">
        <EmptyState title="Workspace not ready" description="Select an organization to view attribution." />
      </div>
    );
  }

  const rangeLabel = range ? `${formatDate(range.from, "MMM d")} – ${formatDate(range.to, "MMM d, yyyy")}` : "This month";

  return (
    <div className="max-w-[1440px] mx-auto space-y-6">
      {/* Header */}
      <div className="flex items-center justify-between gap-4 opacity-0 animate-fade-in">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-foreground">Captured by EmpireVu</h1>
          <p className="text-sm text-muted-foreground mt-0.5">
            Revenue attributed to EmpireVu · {rangeLabel}
          </p>
        </div>
        <div className="flex items-center gap-2">
        <Button variant="outline" size="sm" asChild>
          <Link to="/reports/monthly">
            <CalendarCheck className="w-4 h-4 mr-2" />
            Monthly results
          </Link>
        </Button>
        <Button
          variant="outline"
          size="sm"
          disabled={rows.length === 0}
          onClick={() => downloadCsv(`empirevu-attribution-${range?.from.slice(0, 10) ?? "report"}.csv`, rowsToCsv(rows))}
        >
          <Download className="w-4 h-4 mr-2" />
          Export CSV
        </Button>
        </div>
      </div>

      {isError && <ErrorBanner message="Failed to load attribution report." onRetry={() => refetch()} />}

      {/* Summary tiles */}
      {isLoading ? (
        <SkeletonCard rows={2} />
      ) : summary ? (
        <div className="grid grid-cols-2 md:grid-cols-3 lg:grid-cols-6 gap-3 opacity-0 animate-fade-in" style={{ animationDelay: "80ms" }}>
          <SummaryTile
            label="Collected"
            value={formatCents(summary.paidCentsTotal)}
            hint="deposits paid"
            accent="text-[hsl(var(--success))]"
          />
          <SummaryTile label="Approved" value={formatCents(summary.approvedCentsTotal)} hint="quotes won" />
          <SummaryTile label="Quotes" value={String(summary.quotesCount)} hint="approved or paid" />
          <SummaryTile
            label="Voice AI"
            value={String(summary.voiceAi.count)}
            hint={`${formatCents(summary.voiceAi.paidCents)} collected`}
            accent="text-[hsl(var(--accent-violet))]"
          />
          <SummaryTile
            label="Automated"
            value={String(summary.automation.count)}
            hint={`${formatCents(summary.automation.paidCents)} collected`}
            accent="text-primary"
          />
          <SummaryTile label="Time saved" value={formatSeconds(summary.estimatedTimeSavedSeconds)} hint="est. by automation" />
        </div>
      ) : null}

      {/* Chart by source */}
      <DashboardCard title="Collected by first-touch source" icon={<TrendingUp className="w-3.5 h-3.5" />}>
        {isLoading ? (
          <SkeletonCard rows={3} />
        ) : chartData.length === 0 ? (
          <EmptyState title="No attributed revenue yet" description="Approved or paid quotes will appear here." />
        ) : (
          <div className="h-64 w-full">
            <ResponsiveContainer width="100%" height="100%">
              <BarChart data={chartData} margin={{ top: 8, right: 8, bottom: 8, left: 8 }}>
                <CartesianGrid strokeDasharray="3 3" stroke="hsl(var(--border))" vertical={false} />
                <XAxis dataKey="source" tick={{ fontSize: 12, fill: "hsl(var(--muted-foreground))" }} tickLine={false} axisLine={false} />
                <YAxis
                  tick={{ fontSize: 12, fill: "hsl(var(--muted-foreground))" }}
                  tickLine={false}
                  axisLine={false}
                  tickFormatter={(value: number) => `$${value >= 1000 ? `${(value / 1000).toFixed(0)}k` : value}`}
                />
                <Tooltip
                  cursor={{ fill: "hsl(var(--secondary))", opacity: 0.4 }}
                  contentStyle={{
                    background: "hsl(var(--card))",
                    border: "1px solid hsl(var(--border))",
                    borderRadius: 8,
                    fontSize: 12,
                  }}
                  formatter={(value: number, name: string) => [`$${value.toLocaleString()}`, name === "paid" ? "Collected" : "Approved"]}
                />
                <Bar dataKey="paid" radius={[4, 4, 0, 0]}>
                  {chartData.map((entry, index) => (
                    <Cell key={entry.source} fill={SOURCE_COLORS[index % SOURCE_COLORS.length]} />
                  ))}
                </Bar>
              </BarChart>
            </ResponsiveContainer>
          </div>
        )}
      </DashboardCard>

      {/* Per-quote drill-down */}
      <DashboardCard title="Quotes" icon={<FileText className="w-3.5 h-3.5" />}>
        {isLoading ? (
          <LoadingRows count={6} />
        ) : rows.length === 0 ? (
          <EmptyState title="No quotes in this period" description="Approved or paid quotes will be listed here." />
        ) : (
          <div className="overflow-x-auto">
            <table className="w-full text-sm">
              <thead>
                <tr className="text-left text-[11px] uppercase tracking-wider text-muted-foreground border-b border-border">
                  <th className="py-2 pr-4 font-medium">First touch</th>
                  <th className="py-2 pr-4 font-medium">Touched</th>
                  <th className="py-2 pr-4 font-medium">Signals</th>
                  <th className="py-2 pr-4 font-medium text-right">Approved</th>
                  <th className="py-2 pr-4 font-medium text-right">Collected</th>
                  <th className="py-2 font-medium">Closed</th>
                </tr>
              </thead>
              <tbody>
                {rows.map((row) => (
                  <tr key={row.quoteId} className="border-b border-border/50 hover:bg-secondary/40 transition-colors">
                    <td className="py-2.5 pr-4">
                      <span className="font-medium text-foreground">{row.firstTouchSource}</span>
                      <span className="text-muted-foreground"> · {row.firstTouchChannel}</span>
                    </td>
                    <td className="py-2.5 pr-4 text-muted-foreground tabular-nums">
                      {row.firstTouchAt ? formatDate(row.firstTouchAt, "MMM d") : "—"}
                    </td>
                    <td className="py-2.5 pr-4">
                      <div className="flex items-center gap-1.5">
                        {row.voiceAiInvolved && (
                          <span className="inline-flex items-center gap-1 text-[10px] px-1.5 py-0.5 rounded bg-[hsl(var(--accent-violet))]/10 text-[hsl(var(--accent-violet))]">
                            <Phone className="w-3 h-3" /> Voice AI
                          </span>
                        )}
                        {row.automationInvolved && (
                          <span className="inline-flex items-center gap-1 text-[10px] px-1.5 py-0.5 rounded bg-primary/10 text-primary">
                            <Zap className="w-3 h-3" /> Automated
                          </span>
                        )}
                        {!row.voiceAiInvolved && !row.automationInvolved && <span className="text-[10px] text-muted-foreground">—</span>}
                      </div>
                    </td>
                    <td className="py-2.5 pr-4 text-right tabular-nums text-foreground">{formatCents(row.approvedCents)}</td>
                    <td className="py-2.5 pr-4 text-right tabular-nums font-medium text-[hsl(var(--success))]">
                      {row.paidCents > 0 ? formatCents(row.paidCents) : "—"}
                    </td>
                    <td className="py-2.5 text-muted-foreground tabular-nums">
                      {row.approvedAt ? formatDate(row.approvedAt, "MMM d") : row.paidAt ? formatDate(row.paidAt, "MMM d") : "—"}
                    </td>
                  </tr>
                ))}
              </tbody>
            </table>
          </div>
        )}
      </DashboardCard>

      <p className="text-[11px] text-muted-foreground flex items-center gap-1.5">
        <Sparkles className="w-3 h-3 text-primary" />
        "Collected" counts deposits paid through EmpireVu's Stripe checkout. See docs/attribution.md for how each column is defined.
      </p>
    </div>
  );
}
