import { useState } from "react";
import { Plus, Search, Filter, AlertTriangle, Calendar, User, Building2, Link2, Clock, ChevronDown, Zap, ArrowUpRight, CheckCircle2, Circle, Loader2, Ban, Star } from "lucide-react";
import { cn } from "@/lib/utils";
import { useNavigate } from "react-router-dom";
import TaskDetailPanel from "@/components/tasks/TaskDetailPanel";

const companies = ["All Companies", "A1 Marine Care", "RankLocal", "MarineMecca", "Vitatee"] as const;
const statuses = ["All", "To Do", "In Progress", "Blocked", "Completed"] as const;
const priorities = ["All", "High", "Medium", "Low"] as const;
const assignees = ["All", "Marcus Reid", "Kira Lam", "James Dean", "Ava Singh", "Tom Harris"] as const;

const companyColors: Record<string, string> = {
  "A1 Marine Care": "bg-[hsl(var(--accent-blue))]/15 text-[hsl(var(--accent-blue))]",
  "RankLocal": "bg-[hsl(var(--accent-violet))]/15 text-[hsl(var(--accent-violet))]",
  "MarineMecca": "bg-[hsl(var(--success))]/15 text-[hsl(var(--success))]",
  "Vitatee": "bg-[hsl(var(--warning))]/15 text-[hsl(var(--warning))]",
};

interface Task {
  id: string;
  title: string;
  description: string;
  status: "To Do" | "In Progress" | "Blocked" | "Completed";
  priority: "High" | "Medium" | "Low";
  assignee: string;
  assigneeInitials: string;
  dueDate: string;
  company: string;
  linkedContact?: { name: string; id: string };
  linkedBooking?: string;
  autoGenerated?: string;
  overdue?: boolean;
  comments: number;
  subtasks?: { done: number; total: number };
}

const tasks: Task[] = [
  { id: "TSK-001", title: "Confirm vessel inspection details", description: "Verify scope, confirm inspector availability, and send pre-arrival docs to client.", status: "To Do", priority: "High", assignee: "Marcus Reid", assigneeInitials: "MR", dueDate: "Mar 20", company: "A1 Marine Care", linkedContact: { name: "David Chen", id: "1" }, linkedBooking: "Vessel Inspection — Pacific Voyager", overdue: true, comments: 3, subtasks: { done: 1, total: 4 }, autoGenerated: "booking" },
  { id: "TSK-002", title: "Send SEO performance report to client", description: "Compile monthly report with ranking improvements, traffic data, and recommendations.", status: "In Progress", priority: "Medium", assignee: "Kira Lam", assigneeInitials: "KL", dueDate: "Mar 23", company: "RankLocal", linkedContact: { name: "Sarah Mitchell", id: "2" }, comments: 1, subtasks: { done: 2, total: 3 } },
  { id: "TSK-003", title: "Approve supplier contract for hull paint", description: "Review pricing terms and confirm volume discount before signing.", status: "Blocked", priority: "High", assignee: "James Dean", assigneeInitials: "JD", dueDate: "Mar 21", company: "MarineMecca", linkedContact: { name: "James Morton", id: "3" }, overdue: true, comments: 5 },
  { id: "TSK-004", title: "Schedule product photoshoot", description: "Book photographer, confirm product lineup, arrange studio space.", status: "In Progress", priority: "Low", assignee: "Ava Singh", assigneeInitials: "AS", dueDate: "Mar 25", company: "Vitatee", linkedContact: { name: "Lisa Park", id: "5" }, comments: 0, subtasks: { done: 1, total: 2 } },
  { id: "TSK-005", title: "Prepare Q1 financial summary", description: "Aggregate revenue across all companies, highlight anomalies, forecast Q2.", status: "In Progress", priority: "High", assignee: "Tom Harris", assigneeInitials: "TH", dueDate: "Mar 24", company: "A1 Marine Care", linkedContact: { name: "David Chen", id: "1" }, comments: 2 },
  { id: "TSK-006", title: "Follow up on outstanding invoice #1247", description: "Contact client regarding 30-day overdue payment.", status: "To Do", priority: "High", assignee: "Marcus Reid", assigneeInitials: "MR", dueDate: "Mar 19", company: "A1 Marine Care", linkedContact: { name: "David Chen", id: "1" }, overdue: true, comments: 4, autoGenerated: "pipeline" },
  { id: "TSK-007", title: "Fix checkout flow bug on storefront", description: "Customers reporting 500 error on payment confirmation step.", status: "In Progress", priority: "High", assignee: "Ava Singh", assigneeInitials: "AS", dueDate: "Mar 21", company: "Vitatee", comments: 7, subtasks: { done: 3, total: 5 } },
  { id: "TSK-008", title: "Client feedback analysis — Q4 reviews", description: "Compile and categorize all client feedback from Q4 surveys.", status: "To Do", priority: "Medium", assignee: "Kira Lam", assigneeInitials: "KL", dueDate: "Mar 26", company: "RankLocal", linkedContact: { name: "Sarah Mitchell", id: "2" }, comments: 0 },
  { id: "TSK-009", title: "Onboard new team member", description: "Set up accounts, schedule intro meetings, assign initial training modules.", status: "Completed", priority: "Medium", assignee: "Tom Harris", assigneeInitials: "TH", dueDate: "Mar 18", company: "RankLocal", comments: 2, subtasks: { done: 5, total: 5 } },
  { id: "TSK-010", title: "Update supplier pricing in catalog", description: "Reflect new bulk pricing from Q2 contract negotiations.", status: "Completed", priority: "Low", assignee: "James Dean", assigneeInitials: "JD", dueDate: "Mar 17", company: "MarineMecca", comments: 1 },
  { id: "TSK-011", title: "Prepare booking confirmation for hull cleaning", description: "Generate confirmation document with service scope and pricing.", status: "To Do", priority: "Medium", assignee: "Marcus Reid", assigneeInitials: "MR", dueDate: "Mar 24", company: "A1 Marine Care", linkedBooking: "Hull Cleaning — MV Horizon", autoGenerated: "booking", comments: 0 },
  { id: "TSK-012", title: "Send proposal to new lead", description: "Draft and send service proposal based on initial consultation notes.", status: "To Do", priority: "High", assignee: "Kira Lam", assigneeInitials: "KL", dueDate: "Mar 22", company: "RankLocal", linkedContact: { name: "Rachel Kim", id: "4" }, autoGenerated: "lead", comments: 1 },
];

const statusIcon: Record<string, React.ReactNode> = {
  "To Do": <Circle className="w-3.5 h-3.5 text-muted-foreground" />,
  "In Progress": <Loader2 className="w-3.5 h-3.5 text-[hsl(var(--accent-blue))] animate-[spin_3s_linear_infinite]" />,
  "Blocked": <Ban className="w-3.5 h-3.5 text-[hsl(var(--urgent))]" />,
  "Completed": <CheckCircle2 className="w-3.5 h-3.5 text-[hsl(var(--success))]" />,
};

const statusStyle: Record<string, string> = {
  "To Do": "text-muted-foreground",
  "In Progress": "text-[hsl(var(--accent-blue))]",
  "Blocked": "text-[hsl(var(--urgent))]",
  "Completed": "text-[hsl(var(--success))]",
};

const priorityConfig: Record<string, { bg: string; text: string; dot: string }> = {
  High: { bg: "bg-[hsl(var(--urgent))]/10", text: "text-[hsl(var(--urgent))]", dot: "bg-[hsl(var(--urgent))]" },
  Medium: { bg: "bg-[hsl(var(--warning))]/10", text: "text-[hsl(var(--warning))]", dot: "bg-[hsl(var(--warning))]" },
  Low: { bg: "bg-muted", text: "text-muted-foreground", dot: "bg-muted-foreground" },
};

const autoGenLabels: Record<string, { label: string; icon: React.ReactNode }> = {
  booking: { label: "From booking", icon: <Calendar className="w-3 h-3" /> },
  lead: { label: "From new lead", icon: <User className="w-3 h-3" /> },
  pipeline: { label: "Pipeline change", icon: <Zap className="w-3 h-3" /> },
};

export default function TasksPage() {
  const navigate = useNavigate();
  const [activeStatus, setActiveStatus] = useState<string>("All");
  const [activePriority, setActivePriority] = useState<string>("All");
  const [filterCompany, setFilterCompany] = useState<string>("All Companies");
  const [filterAssignee, setFilterAssignee] = useState<string>("All");
  const [searchQuery, setSearchQuery] = useState("");
  const [selectedTask, setSelectedTask] = useState<Task | null>(null);
  const [showFilters, setShowFilters] = useState(false);

  const filtered = tasks.filter((t) => {
    if (activeStatus !== "All" && t.status !== activeStatus) return false;
    if (activePriority !== "All" && t.priority !== activePriority) return false;
    if (filterCompany !== "All Companies" && t.company !== filterCompany) return false;
    if (filterAssignee !== "All" && t.assignee !== filterAssignee) return false;
    if (searchQuery && !t.title.toLowerCase().includes(searchQuery.toLowerCase()) && !t.id.toLowerCase().includes(searchQuery.toLowerCase())) return false;
    return true;
  });

  const overdueCount = tasks.filter((t) => t.overdue && t.status !== "Completed").length;
  const blockedCount = tasks.filter((t) => t.status === "Blocked").length;
  const todayCount = tasks.filter((t) => t.dueDate === "Mar 22" && t.status !== "Completed").length;

  const statusCounts = {
    "To Do": tasks.filter((t) => t.status === "To Do").length,
    "In Progress": tasks.filter((t) => t.status === "In Progress").length,
    "Blocked": tasks.filter((t) => t.status === "Blocked").length,
    "Completed": tasks.filter((t) => t.status === "Completed").length,
  };

  return (
    <div className="max-w-[1400px] mx-auto space-y-5">
      {/* Header */}
      <div className="flex items-center justify-between opacity-0 animate-fade-in">
        <div>
          <h1 className="text-2xl font-bold tracking-tight text-foreground">Tasks</h1>
          <p className="text-sm text-muted-foreground mt-0.5">{tasks.length} tasks across all companies</p>
        </div>
        <button className="flex items-center gap-1.5 px-4 py-2 rounded-lg text-sm font-medium bg-[hsl(var(--accent-blue))] text-white hover:bg-[hsl(var(--accent-blue))]/90 transition-all active:scale-[0.97] shadow-[0_0_20px_hsl(var(--accent-blue)/0.2)]">
          <Plus className="w-4 h-4" />
          New Task
        </button>
      </div>

      {/* Urgent Banner */}
      {(overdueCount > 0 || blockedCount > 0) && (
        <div className="flex items-center gap-3 px-4 py-3 rounded-xl bg-[hsl(var(--urgent))]/8 border border-[hsl(var(--urgent))]/20 opacity-0 animate-fade-in" style={{ animationDelay: "60ms" }}>
          <div className="p-1.5 rounded-lg bg-[hsl(var(--urgent))]/15">
            <AlertTriangle className="w-4 h-4 text-[hsl(var(--urgent))] animate-pulse" />
          </div>
          <div className="flex-1">
            <p className="text-sm font-medium text-foreground">
              {overdueCount > 0 && <span>{overdueCount} overdue task{overdueCount > 1 ? "s" : ""}</span>}
              {overdueCount > 0 && blockedCount > 0 && <span className="text-muted-foreground mx-1.5">·</span>}
              {blockedCount > 0 && <span>{blockedCount} blocked</span>}
            </p>
          </div>
          <button className="text-xs font-medium text-[hsl(var(--urgent))] hover:underline">View all →</button>
        </div>
      )}

      {/* Stats Row */}
      <div className="grid grid-cols-4 gap-3 opacity-0 animate-fade-in" style={{ animationDelay: "100ms" }}>
        {(Object.entries(statusCounts) as [string, number][]).map(([status, count]) => (
          <button
            key={status}
            onClick={() => setActiveStatus(activeStatus === status ? "All" : status)}
            className={cn(
              "flex items-center gap-3 px-4 py-3 rounded-xl border transition-all active:scale-[0.98]",
              activeStatus === status
                ? "bg-[hsl(var(--surface-2))] border-[hsl(var(--accent-blue))]/30"
                : "bg-[hsl(var(--surface-1))] border-border hover:border-border/80"
            )}
          >
            {statusIcon[status]}
            <div className="text-left">
              <p className="text-lg font-semibold text-foreground tabular-nums">{count}</p>
              <p className="text-[11px] text-muted-foreground">{status}</p>
            </div>
          </button>
        ))}
      </div>

      {/* Filters Bar */}
      <div className="flex items-center justify-between opacity-0 animate-fade-in" style={{ animationDelay: "140ms" }}>
        <div className="flex items-center gap-2">
          {/* Status Tabs */}
          <div className="flex items-center gap-0.5 bg-[hsl(var(--surface-1))] rounded-lg p-0.5 border border-border">
            {statuses.map((s) => (
              <button
                key={s}
                onClick={() => setActiveStatus(s)}
                className={cn(
                  "px-3 py-1.5 rounded-md text-xs font-medium transition-all",
                  activeStatus === s
                    ? "bg-[hsl(var(--surface-3))] text-foreground shadow-sm"
                    : "text-muted-foreground hover:text-foreground"
                )}
              >
                {s}
              </button>
            ))}
          </div>

          {/* Company Filter */}
          <div className="relative">
            <select
              value={filterCompany}
              onChange={(e) => setFilterCompany(e.target.value)}
              className="appearance-none bg-[hsl(var(--surface-1))] border border-border rounded-lg pl-3 pr-7 py-1.5 text-xs font-medium text-foreground cursor-pointer focus:outline-none focus:ring-1 focus:ring-[hsl(var(--accent-blue))]/50"
            >
              {companies.map((c) => <option key={c} value={c}>{c}</option>)}
            </select>
            <ChevronDown className="absolute right-2 top-1/2 -translate-y-1/2 w-3 h-3 text-muted-foreground pointer-events-none" />
          </div>

          <button
            onClick={() => setShowFilters(!showFilters)}
            className={cn(
              "flex items-center gap-1.5 px-3 py-1.5 rounded-lg text-xs font-medium border transition-colors",
              showFilters ? "bg-[hsl(var(--surface-2))] border-[hsl(var(--accent-blue))]/30 text-foreground" : "border-border text-muted-foreground hover:text-foreground hover:bg-[hsl(var(--surface-1))]"
            )}
          >
            <Filter className="w-3 h-3" />
            Filters
          </button>
        </div>

        <div className="relative">
          <Search className="absolute left-2.5 top-1/2 -translate-y-1/2 w-3.5 h-3.5 text-muted-foreground" />
          <input
            type="text"
            value={searchQuery}
            onChange={(e) => setSearchQuery(e.target.value)}
            placeholder="Search tasks..."
            className="bg-[hsl(var(--surface-1))] border border-border rounded-lg pl-8 pr-3 py-1.5 text-sm text-foreground placeholder:text-muted-foreground focus:outline-none focus:ring-1 focus:ring-[hsl(var(--accent-blue))]/50 w-56"
          />
        </div>
      </div>

      {/* Extended Filters */}
      {showFilters && (
        <div className="flex items-center gap-3 px-4 py-3 rounded-xl bg-[hsl(var(--surface-1))] border border-border opacity-0 animate-fade-in">
          <span className="text-xs text-muted-foreground">Priority:</span>
          <div className="flex gap-1">
            {priorities.map((p) => (
              <button
                key={p}
                onClick={() => setActivePriority(p)}
                className={cn(
                  "px-2.5 py-1 rounded-md text-xs font-medium transition-colors",
                  activePriority === p ? "bg-[hsl(var(--surface-3))] text-foreground" : "text-muted-foreground hover:text-foreground"
                )}
              >
                {p}
              </button>
            ))}
          </div>
          <div className="w-px h-4 bg-border" />
          <span className="text-xs text-muted-foreground">Assignee:</span>
          <div className="relative">
            <select
              value={filterAssignee}
              onChange={(e) => setFilterAssignee(e.target.value)}
              className="appearance-none bg-[hsl(var(--surface-2))] border border-border rounded-md pl-2.5 pr-6 py-1 text-xs text-foreground cursor-pointer focus:outline-none"
            >
              {assignees.map((a) => <option key={a} value={a}>{a}</option>)}
            </select>
            <ChevronDown className="absolute right-1.5 top-1/2 -translate-y-1/2 w-3 h-3 text-muted-foreground pointer-events-none" />
          </div>
        </div>
      )}

      {/* Task Table */}
      <div className="bg-[hsl(var(--surface-1))] border border-border rounded-xl overflow-hidden opacity-0 animate-fade-in" style={{ animationDelay: "180ms" }}>
        <table className="w-full">
          <thead>
            <tr className="border-b border-border">
              <th className="text-left text-[11px] font-medium text-muted-foreground uppercase tracking-wider px-4 py-3">Task</th>
              <th className="text-left text-[11px] font-medium text-muted-foreground uppercase tracking-wider px-4 py-3">Status</th>
              <th className="text-left text-[11px] font-medium text-muted-foreground uppercase tracking-wider px-4 py-3">Priority</th>
              <th className="text-left text-[11px] font-medium text-muted-foreground uppercase tracking-wider px-4 py-3">Assignee</th>
              <th className="text-left text-[11px] font-medium text-muted-foreground uppercase tracking-wider px-4 py-3">Due</th>
              <th className="text-left text-[11px] font-medium text-muted-foreground uppercase tracking-wider px-4 py-3">Linked</th>
              <th className="text-left text-[11px] font-medium text-muted-foreground uppercase tracking-wider px-4 py-3">Company</th>
            </tr>
          </thead>
          <tbody>
            {filtered.map((task) => (
              <tr
                key={task.id}
                onClick={() => setSelectedTask(task)}
                className={cn(
                  "border-b border-border/40 last:border-b-0 cursor-pointer transition-colors group",
                  task.overdue && task.status !== "Completed" && "bg-[hsl(var(--urgent))]/[0.03]",
                  selectedTask?.id === task.id ? "bg-[hsl(var(--accent-blue))]/[0.06]" : "hover:bg-[hsl(var(--surface-2))]/50"
                )}
              >
                {/* Task */}
                <td className="px-4 py-3 max-w-[320px]">
                  <div className="flex items-start gap-2.5">
                    <div className="mt-0.5">{statusIcon[task.status]}</div>
                    <div className="min-w-0">
                      <div className="flex items-center gap-2">
                        <span className="text-[11px] font-mono text-muted-foreground">{task.id}</span>
                        {task.overdue && task.status !== "Completed" && (
                          <span className="text-[10px] font-semibold px-1.5 py-0.5 rounded bg-[hsl(var(--urgent))]/15 text-[hsl(var(--urgent))]">OVERDUE</span>
                        )}
                        {task.autoGenerated && (
                          <span className="flex items-center gap-1 text-[10px] font-medium px-1.5 py-0.5 rounded bg-[hsl(var(--accent-violet))]/10 text-[hsl(var(--accent-violet))]">
                            <Zap className="w-2.5 h-2.5" />
                            {autoGenLabels[task.autoGenerated].label}
                          </span>
                        )}
                      </div>
                      <p className={cn(
                        "text-sm font-medium mt-0.5 truncate",
                        task.status === "Completed" ? "text-muted-foreground line-through" : "text-foreground"
                      )}>
                        {task.title}
                      </p>
                      {task.subtasks && (
                        <div className="flex items-center gap-1.5 mt-1">
                          <div className="w-16 h-1 rounded-full bg-[hsl(var(--surface-3))] overflow-hidden">
                            <div
                              className="h-full rounded-full bg-[hsl(var(--accent-blue))]"
                              style={{ width: `${(task.subtasks.done / task.subtasks.total) * 100}%` }}
                            />
                          </div>
                          <span className="text-[10px] text-muted-foreground tabular-nums">{task.subtasks.done}/{task.subtasks.total}</span>
                        </div>
                      )}
                    </div>
                  </div>
                </td>

                {/* Status */}
                <td className="px-4 py-3">
                  <span className={cn("text-xs font-medium", statusStyle[task.status])}>{task.status}</span>
                </td>

                {/* Priority */}
                <td className="px-4 py-3">
                  <span className={cn("inline-flex items-center gap-1.5 text-xs font-medium px-2 py-0.5 rounded-md", priorityConfig[task.priority].bg, priorityConfig[task.priority].text)}>
                    <span className={cn("w-1.5 h-1.5 rounded-full", priorityConfig[task.priority].dot)} />
                    {task.priority}
                  </span>
                </td>

                {/* Assignee */}
                <td className="px-4 py-3">
                  <div className="flex items-center gap-2">
                    <div className="w-6 h-6 rounded-full bg-[hsl(var(--surface-3))] flex items-center justify-center text-[10px] font-semibold text-foreground">
                      {task.assigneeInitials}
                    </div>
                    <span className="text-xs text-muted-foreground hidden xl:inline">{task.assignee.split(" ")[0]}</span>
                  </div>
                </td>

                {/* Due */}
                <td className="px-4 py-3">
                  <span className={cn(
                    "text-xs tabular-nums",
                    task.overdue && task.status !== "Completed" ? "text-[hsl(var(--urgent))] font-medium" : "text-muted-foreground"
                  )}>
                    {task.dueDate}
                  </span>
                </td>

                {/* Linked */}
                <td className="px-4 py-3">
                  <div className="flex items-center gap-1.5">
                    {task.linkedContact && (
                      <button
                        onClick={(e) => { e.stopPropagation(); navigate(`/crm/${task.linkedContact!.id}`); }}
                        className="flex items-center gap-1 text-[11px] font-medium px-1.5 py-0.5 rounded bg-[hsl(var(--surface-2))] text-[hsl(var(--accent-blue))] hover:bg-[hsl(var(--surface-3))] transition-colors"
                      >
                        <User className="w-2.5 h-2.5" />
                        {task.linkedContact.name.split(" ")[0]}
                      </button>
                    )}
                    {task.linkedBooking && (
                      <button
                        onClick={(e) => { e.stopPropagation(); navigate("/calendar"); }}
                        className="flex items-center gap-1 text-[11px] font-medium px-1.5 py-0.5 rounded bg-[hsl(var(--surface-2))] text-[hsl(var(--accent-violet))] hover:bg-[hsl(var(--surface-3))] transition-colors"
                      >
                        <Calendar className="w-2.5 h-2.5" />
                        Booking
                      </button>
                    )}
                    {!task.linkedContact && !task.linkedBooking && (
                      <span className="text-[11px] text-muted-foreground/50">—</span>
                    )}
                  </div>
                </td>

                {/* Company */}
                <td className="px-4 py-3">
                  <span className={cn("text-[11px] font-medium px-2 py-0.5 rounded-md", companyColors[task.company])}>
                    {task.company}
                  </span>
                </td>
              </tr>
            ))}
          </tbody>
        </table>

        {filtered.length === 0 && (
          <div className="flex flex-col items-center justify-center py-16 text-center">
            <div className="p-3 rounded-xl bg-[hsl(var(--surface-2))] mb-3">
              <CheckCircle2 className="w-6 h-6 text-muted-foreground" />
            </div>
            <p className="text-sm font-medium text-foreground">No tasks found</p>
            <p className="text-xs text-muted-foreground mt-1">Try adjusting your filters</p>
          </div>
        )}
      </div>

      {/* Task Detail Panel */}
      {selectedTask && (
        <TaskDetailPanel
          task={selectedTask}
          onClose={() => setSelectedTask(null)}
          onNavigateContact={(id) => navigate(`/crm/${id}`)}
          onNavigateCalendar={() => navigate("/calendar")}
        />
      )}
    </div>
  );
}
