import type { Json } from "@/server/db/database.types";
import {
  assertCompanyInOrganization,
  type TenantServiceContext,
} from "@/server/services/shared";

/**
 * Revenue attribution (Task 14): "Revenue captured by EmpireVu" — the summary card + the
 * per-quote drill-down that reads `revenue_attribution_v` / `ui_attribution_summary`.
 *
 * The SQL is the source of truth for first-touch and involvement; `deriveFirstTouch` here
 * is a PURE reference implementation of the same rule, golden-tested so the SQL and the app
 * can never silently disagree (mirrors Task 12's `deriveNeedsReply`). `monthRangeInTimeZone`
 * is the pure, DST-safe period boundary used for the default "this month" window.
 */

// ── Public shapes ─────────────────────────────────────────────────────────────

export interface AttributionBreakdownEntry {
  key: string;
  count: number;
  approvedCents: number;
  paidCents: number;
}

export interface AttributionSegment {
  count: number;
  approvedCents: number;
  paidCents: number;
}

export interface AttributionSummary {
  quotesCount: number;
  approvedCentsTotal: number;
  paidCentsTotal: number;
  voiceAi: AttributionSegment;
  automation: AttributionSegment;
  estimatedTimeSavedSeconds: number;
  bySource: AttributionBreakdownEntry[];
  byChannel: AttributionBreakdownEntry[];
}

export interface AttributionRow {
  quoteId: string;
  contactId: string | null;
  companyId: string | null;
  autoGenerated: boolean;
  firstTouchSource: string;
  firstTouchChannel: string;
  firstTouchAt: string | null;
  voiceAiInvolved: boolean;
  automationInvolved: boolean;
  approvedCents: number;
  paidCents: number;
  approvedAt: string | null;
  paidAt: string | null;
}

export interface PeriodRange {
  from: string;
  to: string;
}

interface AttributionQueryInput {
  companyId?: string | null;
  from?: string | null;
  to?: string | null;
}

// ── first_touch reference rule (mirrors revenue_attribution_v exactly) ──────────

export interface FirstTouchInputs {
  /** raw_leads rows for the contact (rank 0, channel 'web'). */
  rawLeads: Array<{ createdAt: string; source: string | null; sourceSite: string | null }>;
  /** inbound retell_calls (rank 1, channel 'voice') — ts is coalesce(received_at, created_at). */
  inboundCalls: Array<{ at: string }>;
  /** inbound message_log rows (rank 2, channel = email|sms) — ts is created_at. */
  inboundMessages: Array<{ createdAt: string; channel: string }>;
  /** fallback when the quote's contact has no touch (or no contact). */
  contactCreatedAt: string | null;
}

export interface FirstTouch {
  source: string;
  channel: string;
  at: string | null;
}

/**
 * The earliest touch on the contact across web leads, inbound voice, and inbound messages.
 * On an exact-timestamp tie, lower rank wins (raw_leads 0 < voice 1 < message 2), matching
 * the view's `order by ts asc, rnk asc`. With no touches, first_touch is the contact's own
 * created_at with source/channel 'manual'.
 */
export function deriveFirstTouch(inputs: FirstTouchInputs): FirstTouch {
  const candidates: Array<{ ts: string; rank: number; source: string; channel: string }> = [];

  for (const lead of inputs.rawLeads) {
    candidates.push({
      ts: lead.createdAt,
      rank: 0,
      source: lead.source ?? lead.sourceSite ?? "web",
      channel: "web",
    });
  }
  for (const call of inputs.inboundCalls) {
    candidates.push({ ts: call.at, rank: 1, source: "retell", channel: "voice" });
  }
  for (const message of inputs.inboundMessages) {
    candidates.push({
      ts: message.createdAt,
      rank: 2,
      source: message.channel,
      channel: message.channel === "email" ? "email" : "sms",
    });
  }

  const [first] = candidates
    .filter((candidate) => Boolean(candidate.ts) && Number.isFinite(Date.parse(candidate.ts)))
    .sort((left, right) => {
      const delta = Date.parse(left.ts) - Date.parse(right.ts);
      return delta !== 0 ? delta : left.rank - right.rank;
    });

  if (first) {
    return { source: first.source, channel: first.channel, at: first.ts };
  }
  return { source: "manual", channel: "manual", at: inputs.contactCreatedAt };
}

// ── Period boundaries (pure, DST-safe; same technique as workflow timing.ts) ────

/** Offset (localWallClock − UTC) in ms for an instant, in an IANA zone. */
function tzOffsetMs(utcMs: number, timeZone: string): number {
  const parts = new Intl.DateTimeFormat("en-US", {
    timeZone,
    hourCycle: "h23",
    year: "numeric",
    month: "numeric",
    day: "numeric",
    hour: "numeric",
    minute: "numeric",
    second: "numeric",
  }).formatToParts(new Date(utcMs));
  const map: Record<string, number> = {};
  for (const part of parts) if (part.type !== "literal") map[part.type] = Number(part.value);
  const asIfUtc = Date.UTC(map.year, map.month - 1, map.day, map.hour, map.minute, map.second);
  return asIfUtc - utcMs;
}

/**
 * The `[from, to)` UTC instants bounding the local calendar month that contains `nowMs` in
 * the given zone. DST-safe: each boundary's offset is computed at its own wall-clock, so a
 * month straddling a spring-forward / fall-back still starts and ends at local midnight.
 */
export function monthRangeInTimeZone(timeZone: string, nowMs: number): PeriodRange {
  const parts = new Intl.DateTimeFormat("en-CA", {
    timeZone,
    year: "numeric",
    month: "2-digit",
    day: "2-digit",
  }).formatToParts(new Date(nowMs));
  const map: Record<string, number> = {};
  for (const part of parts) if (part.type !== "literal") map[part.type] = Number(part.value);

  // Date.UTC handles month overflow, so month index `map.month` is next month's start.
  const fromNaive = Date.UTC(map.year, map.month - 1, 1, 0, 0, 0);
  const toNaive = Date.UTC(map.year, map.month, 1, 0, 0, 0);

  return {
    from: new Date(fromNaive - tzOffsetMs(fromNaive, timeZone)).toISOString(),
    to: new Date(toNaive - tzOffsetMs(toNaive, timeZone)).toISOString(),
  };
}

/** companies.timezone → BUSINESS_TIMEZONE → America/Toronto (Task 9 fallback chain). */
export function fallbackTimeZone(): string {
  return process.env.BUSINESS_TIMEZONE?.trim() || "America/Toronto";
}

export async function resolveCompanyTimeZone(
  context: TenantServiceContext,
  companyId: string | null | undefined,
): Promise<string> {
  if (!companyId) return fallbackTimeZone();
  const { data } = await context.supabase
    .from("companies")
    .select("timezone")
    .eq("organization_id", context.organizationId)
    .eq("id", companyId)
    .maybeSingle();
  return (data as { timezone: string | null } | null)?.timezone?.trim() || fallbackTimeZone();
}

// ── Reads ───────────────────────────────────────────────────────────────────

function numberOf(value: Json | undefined): number {
  if (typeof value === "number" && Number.isFinite(value)) return value;
  const parsed = Number(value ?? 0);
  return Number.isFinite(parsed) ? parsed : 0;
}

function toBreakdown(value: Json | null | undefined): AttributionBreakdownEntry[] {
  if (!value || typeof value !== "object" || Array.isArray(value)) return [];
  const entries: AttributionBreakdownEntry[] = [];
  for (const [key, raw] of Object.entries(value)) {
    const record = raw && typeof raw === "object" && !Array.isArray(raw) ? (raw as Record<string, Json>) : {};
    entries.push({
      key,
      count: numberOf(record.count),
      approvedCents: numberOf(record.approved_cents),
      paidCents: numberOf(record.paid_cents),
    });
  }
  // Highest paid first, then approved, then count — deterministic tie-break on key.
  entries.sort(
    (left, right) =>
      right.paidCents - left.paidCents ||
      right.approvedCents - left.approvedCents ||
      right.count - left.count ||
      left.key.localeCompare(right.key),
  );
  return entries;
}

export async function getAttributionSummary(
  context: TenantServiceContext,
  input: AttributionQueryInput = {},
): Promise<AttributionSummary> {
  await assertCompanyInOrganization(context, input.companyId);
  const { data, error } = await context.supabase.rpc("ui_attribution_summary", {
    p_org_id: context.organizationId,
    p_company_id: input.companyId ?? undefined,
    p_from: input.from ?? undefined,
    p_to: input.to ?? undefined,
  });
  if (error) {
    throw error;
  }
  const row = data?.[0];

  return {
    quotesCount: row?.quotes_count ?? 0,
    approvedCentsTotal: numberOf(row?.approved_cents_total),
    paidCentsTotal: numberOf(row?.paid_cents_total),
    voiceAi: {
      count: row?.voice_ai_count ?? 0,
      approvedCents: numberOf(row?.voice_ai_approved_cents),
      paidCents: numberOf(row?.voice_ai_paid_cents),
    },
    automation: {
      count: row?.automation_count ?? 0,
      approvedCents: numberOf(row?.automation_approved_cents),
      paidCents: numberOf(row?.automation_paid_cents),
    },
    estimatedTimeSavedSeconds: numberOf(row?.estimated_time_saved_seconds),
    bySource: toBreakdown(row?.by_source),
    byChannel: toBreakdown(row?.by_channel),
  };
}

// PostgREST can't order by / filter on coalesce(approved_at, paid_at), so the period
// cohort and ordering are applied in TS (below) rather than via an un-executed filter
// string. This caps how many of an org's lifetime approved/paid quotes we pull; the report
// is monthly + per-company, so it is never approached in practice.
const MAX_ATTRIBUTION_ROWS = 5000;

/** The row's close instant — coalesce(approved_at, paid_at) — in ms, or null. */
function closedAtMs(row: AttributionRow): number | null {
  const parsed = Date.parse(row.approvedAt ?? row.paidAt ?? "");
  return Number.isFinite(parsed) ? parsed : null;
}

export async function listAttribution(
  context: TenantServiceContext,
  input: AttributionQueryInput & { limit?: number } = {},
): Promise<AttributionRow[]> {
  await assertCompanyInOrganization(context, input.companyId);

  let query = context.supabase
    .from("revenue_attribution_v")
    .select("*")
    .eq("organization_id", context.organizationId);

  if (input.companyId) {
    query = query.eq("company_id", input.companyId);
  }

  const { data, error } = await query.limit(MAX_ATTRIBUTION_ROWS);
  if (error) {
    throw error;
  }

  let rows: AttributionRow[] = (data ?? []).map((row) => ({
    quoteId: row.quote_id ?? "",
    contactId: row.contact_id,
    companyId: row.company_id,
    autoGenerated: row.auto_generated ?? false,
    firstTouchSource: row.first_touch_source ?? "manual",
    firstTouchChannel: row.first_touch_channel ?? "manual",
    firstTouchAt: row.first_touch_at,
    voiceAiInvolved: row.voice_ai_involved ?? false,
    automationInvolved: row.automation_involved ?? false,
    approvedCents: numberOf(row.approved_cents),
    paidCents: numberOf(row.paid_cents),
    approvedAt: row.approved_at,
    paidAt: row.paid_at,
  }));

  // Period cohort: coalesce(approved_at, paid_at) ∈ [from, to) — the same rule the RPC
  // uses, kept authoritative here so correctness never depends on a PostgREST filter string.
  if (input.from && input.to) {
    const fromMs = Date.parse(input.from);
    const toMs = Date.parse(input.to);
    rows = rows.filter((row) => {
      const closed = closedAtMs(row);
      return closed !== null && closed >= fromMs && closed < toMs;
    });
  }

  // Most recently closed first.
  rows.sort((left, right) => (closedAtMs(right) ?? 0) - (closedAtMs(left) ?? 0));

  return typeof input.limit === "number" ? rows.slice(0, input.limit) : rows;
}
