-- CrankLeads setup follow-ups (docs/crankleads-purchase.md → "Setup follow-ups").
--
-- A buyer who pays and never finishes setup is chased automatically: reminders at business
-- day 1, 3, 5 and 10 after provisioning (email + SMS to the owner, company-local 9:00–18:00,
-- weekdays only), each naming the next unfinished step with a one-click deep link; the day-10
-- reminder also tells the operator (OWNER_EMAIL) the buyer is stuck. When the setup checklist
-- first reports the account live, crankleads_purchases.live_at is stamped and one "you're live"
-- email + SMS goes out. Runs inside the workflow-event worker's scheduler pass.
--
-- Depends on voice_numbers.forwarding_verified_at, added by 20261004120000 (feat/forwarding-verify,
-- applied BEFORE this file). This migration does NOT create it.
--
-- Additive only. Rollback: supabase/rollback/20261004130000_setup_followups.down.sql.

-- ── crankleads_purchases: live stamp + reminder opt-out ─────────────────────
-- live_at: when the setup checklist first reported every required step done (set once by the
--   follow-up job; never cleared). The purchase row is the per-buyer record of the sale, so
--   "when did this buyer go live" lives next to paid_at / provisioned_at.
-- setup_reminders_stopped_at: the owner clicked "stop these reminders" (email footer link).
-- setup_reminders_stop_token: the unguessable token in that link (random, generated by the
--   job on the first reminder; 48 hex chars). The table stays service-role only (no policies).
alter table public.crankleads_purchases
  add column if not exists live_at timestamptz,
  add column if not exists setup_reminders_stopped_at timestamptz,
  add column if not exists setup_reminders_stop_token text;

create unique index if not exists crankleads_purchases_stop_token_idx
  on public.crankleads_purchases (setup_reminders_stop_token)
  where setup_reminders_stop_token is not null;

-- The follow-up scan: provisioned purchases that are not live yet.
create index if not exists crankleads_purchases_not_live_idx
  on public.crankleads_purchases (provisioned_at)
  where status = 'provisioned' and live_at is null;

-- ── crankleads_setup_followups (send log + idempotency guard) ───────────────
-- One row per (purchase, stage). The job INSERTS (claims) the row before sending, so a retry,
-- a second worker or a double run can never send the same stage twice (unique purchase+stage),
-- and at most one reminder goes out per purchase per company-local day (partial unique index).
-- Written only by the worker (service role, sanctioned: workers/jobs); org members may read it.
create table if not exists public.crankleads_setup_followups (
  id uuid primary key default gen_random_uuid(),
  organization_id uuid not null references public.organizations (id) on delete cascade,
  company_id uuid not null,
  purchase_id uuid not null references public.crankleads_purchases (id) on delete cascade,
  stage text not null check (stage in ('day1', 'day3', 'day5', 'day10', 'live')),
  -- company-local calendar date of the send (YYYY-MM-DD in companies.timezone)
  local_date date not null,
  next_step text,
  steps_left integer check (steps_left is null or steps_left >= 0),
  email_status text,
  sms_status text,
  operator_status text,
  detail jsonb not null default '{}'::jsonb,
  created_at timestamptz not null default timezone('utc', now()),
  updated_at timestamptz not null default timezone('utc', now()),
  foreign key (company_id, organization_id) references public.companies (id, organization_id) on delete cascade,
  unique (purchase_id, stage)
);

create unique index if not exists crankleads_setup_followups_one_reminder_per_day
  on public.crankleads_setup_followups (purchase_id, local_date)
  where stage <> 'live';

create index if not exists crankleads_setup_followups_org_company_idx
  on public.crankleads_setup_followups (organization_id, company_id, created_at desc);

drop trigger if exists crankleads_setup_followups_set_updated_at on public.crankleads_setup_followups;
create trigger crankleads_setup_followups_set_updated_at
before update on public.crankleads_setup_followups
for each row execute procedure public.touch_updated_at();

alter table public.crankleads_setup_followups enable row level security;

drop policy if exists "crankleads_setup_followups_members_select" on public.crankleads_setup_followups;
create policy "crankleads_setup_followups_members_select"
  on public.crankleads_setup_followups for select
  using (public.is_organization_member(organization_id));
-- No insert/update/delete policies: writes are service-role only (the worker).
